### ISSUE TITLE
TRG 1.02 / TRG 5.07: Documentation misses dependency update

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/policy-hub#141]
### Current Behavior

`./charts/policy-hub/README.md` misses `helm dependency update` and thus does not install with the provided instructions.

### Expected Behavior

- Per [TRG 1.02](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2#best-practices) the `INSTALL.md` / `README.md` should install successfully.
- Per [TRG 5.07](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07#installing-a-chart-with-dependencies) dependencies should be updated.

**Comment by evegufy** [comment]
@tom-rm-meyer-ISST thank you for performing the Quality Gate Review for the 24.05 release!
When installing a released chart from a chart repository (which is assumed here), it doesn't make sense to perform a helm dependency update, could you please close that issue?
helm dependency update needs to be executed if you still need to the download the dependencies of the Chart.yaml, which is necessary if you install the chart from locally checked out repository.

**Comment by tom-rm-meyer-ISST** [comment]
@evegufy Thanks for clarifying! Missed that detail. Thus, not needed :)
