### ISSUE TITLE
TRG 7.02: Missing license headers on a few files

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/policy-hub#142]
### Current Behavior

Following files are lacking a license header:

- src/PolicyHub.Entities/Entities/IActiveEntity.cs
- src/PolicyHub.Migrations/Seeder/BatchUpdateSeeder.cs
- tests/database/PolicyHub.DbAccess.Tests/HubRepositories.cs

### Expected Behavior

Per [TRG 7.02](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02#copyright-and-license-header), license headers are needed.

**Comment by evegufy** [comment]
done
