### ISSUE TITLE
Align Seeding Data and Validation Rules with 24.08 Standard

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/policy-hub#165]
**Description:**
The policy hub requires an update to its seeding data and validation rules to conform to the new standard release 24.08. This involves the removal of all credentials associated with the "technical_key": "FrameworkAgreement" and the addition of the new "DataExchangeGovernance:1.0".

**Affected File:**
- [policy_attributes.json](https://github.com/eclipse-tractusx/policy-hub/blob/main/src/database/PolicyHub.Migrations/Seeder/Data/policy_attributes.json)

**Acceptance Criteria:**
- All credentials under "technical_key": "FrameworkAgreement" with "type" "5" are successfully removed from the seeding data.
- The "DataExchangeGovernanceCredential:1.0" is correctly added to the seeding data (release image).
- The policy hub's validation rules are updated to accommodate the new standard release 24.08. `test by PO`
- The system operates correctly with the updated seeding data and validation rules, without any issues.
- All changes are well-documented and communicated.

**Comment by Sebastian-Wurm** [comment]
@jjeroch: is this already done?

**Comment by Phil91** [comment]
@Sebastian-Wurm the `DataExchangeGovernance` is available in v1.1.0
