### ISSUE TITLE
[E2E]: Policy Hub Contract Reference dropdown field

### ISSUE THREAD

**Issue by ciprianherciu** [eclipse-tractusx/policy-hub#186]
### Current Behavior
Contract Reference Option does appear in Policy Hub, but the field type is a dropdown one.
Although there is a note that the bilateral contract name should be added in the right operand there is no field to do it in.
Issue now it is not possible to add the Bilateral contract name.
Contract Reference is a dropdown field. Only Option is {bilateralContractName}
![image](https://github.com/user-attachments/assets/f9245c2f-1d47-46ce-83e2-d637565e9dac)

### Expected Behavior

1. The ContractReffrence dropdown should contain possible Contract Reference names (as it is for UsagePupose or FrameworkAgreement)
2. ContractReffrence should be a text field where the bilateral contract name is writeable

### Steps To Reproduce
Create a policy using Policy Hub

**Comment by jjeroch** [comment]
@ciprianherciu  can you please add a better description. It is not possible to understand what you want.
We can not support such tickets.

On top of that, please use screenshots where possible.

**Comment by ciprianherciu** [comment]
@jjeroch The Contract Reference field is present.
Type of the field is a Dropdown.
Only Dropdown option is {bilateralContractName}. 
Is this is how it supposed to work? 
Other Dropdown fields from Policy Hub have options

**Comment by jjeroch** [comment]
@ciprianherciu what do you mean with dropdown, the contract reference is not a dropdown field. The contractReference is a bilateral contract name which is created on paper between two parties. We can off course not know the contract name; the right operand is a free-text-field

**Comment by ciprianherciu** [comment]
@jjeroch 
To use the Policy Hub, we have categorized  the fields based on the attributes:
	•	If the attribute is static than the field will be a dropdown field
	•	If the attribute is Regex than it will be an input field
f.e.:
![image](https://github.com/user-attachments/assets/1084f01a-fc19-44ad-b628-dc64ba2e0410)

Since ContractReffrence has the attribute Static which will be represented in SDE as a dropdown field.
If it is expected that the bilateral contract name should be written in a text field, could we adjust the attribute to Regex, as it is for the BPNL?

**Comment by jjeroch** [comment]
@ciprianherciu it is always a huge risk which you take if you implement an logic which is not supported/not shared/proposed by the actual data provider. You implemented based on own assumptions of type meanings. Thats not recommended.
For me the regex is not making sense since there are no limitations; regexes are important if you have a fix given set of characters. However leaving the decision for @MaximilianHauer

**Comment by evegufy** [comment]
relates to https://github.com/eclipse-tractusx/policy-hub/issues/176

**Comment by MaximilianHauer** [comment]
@ciprianherciu we should not adjust the policy configuration only that it fits your needs. if you notice that the implementation of yours is not fitting then this is the place to improve on and not the setup of the policy.
