### ISSUE TITLE
Fix tractusx metadata

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/policy-hub#4]
Hi @Phil91 

I've noticed your policy-hub repo isn't properly listed (doesn't show product name) in the quality dashboard:

![obraz](https://github.com/eclipse-tractusx/policy-hub/assets/7613143/470691f2-8c92-4824-aec0-9b637b7f6fce)

That is because of incorrect configuration of your .tractusx metadata file for leading repositories. 
Please refer to https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5 or other leading repos configuration in our org.
Don't hesitate to contact me in case of any issues, happy to help.

**Comment by Phil91** [comment]
> Hi @Phil91
> 
> I've noticed your policy-hub repo isn't properly listed (doesn't show product name) in the quality dashboard:
> 
> ![obraz](https://user-images.githubusercontent.com/7613143/282409922-470691f2-8c92-4824-aec0-9b637b7f6fce.png)
> 
> That is because of incorrect configuration of your .tractusx metadata file for leading repositories. Please refer to https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5 or other leading repos configuration in our org. Don't hesitate to contact me in case of any issues, happy to help.

Hey @tomaszbarwicki 
thanks for the info. I'll check and fix it.

**Comment by Phil91** [comment]
@tomaszbarwicki sigi provided a fix for it. i double checked the board. Name is set correctly now.
I'll look into the other breaking checks. For now i'm going to close that issue, is that okay for you?

**Comment by tomaszbarwicki** [comment]
Thanks @Phil91 for the fix, looks good now :)
