### ISSUE TITLE
Policy Hub - BPNL Policy Handling

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/policy-hub#44]
### Summary
With the latest decision of setting policy rules of 24.05. release - the policy of BPNLs have slidely changed.

Access Policy:

- as mentioned in ticket #43 access policies support OR connection
We are currently using the operand "in" if multiple BPNLs are mentioned as policy value for the policy rule BPN.
With the latest updates; following rules got set:

- rightOperand can only include one BPNL
- the operator for BPNLs is always equal; nothing else is allowed
- if the user sets multiple BPNLs for access; the constraint is set as an "or" constraint ("constraintOperand": "Or")
- for usage policies only a single BPNL is allowed

**Comment by AnuragNagpure** [comment]
@jjeroch Need some clarification regarding setting multiple BPNLs access. Can you please help us.

@Phil91

**Comment by jjeroch** [comment]
@AnuragNagpure  & @Phil91  more details regarding the expected solution

If the user sends following request via POST

```json
{
  "policyType": "Access",
  "constraintOperand": "And",
  "constraints": [
    {
      "key": "BusinessPartnerNumber",
      "operator": "Equals",
      "value": "{BPNL...1}"
    }
  ]
}
```

**Respond**: with the policy template and the BusinessPartnerNumber

<br>
<br>

If the user sends following request via POST

```json
{
  "policyType": "Access",
  "constraintOperand": "And",
  "constraints": [
    {
      "key": "BusinessPartnerNumber",
      "operator": "Equals",
      "value": "{BPNL...1},{BPNL...2},{BPNL...3} "
    }
  ]
}
```

**Respond**: Error: only a single value BPNL is allowed with an "AND" constraint

<br>
<br>

If the user sends following request via POST

```json
{
  "policyType": "Access",
  "constraintOperand": "Or",
  "constraints": [
    {
      "key": "BusinessPartnerNumber",
      "operator": "Equals",
      "value": "{BPNL...1},{BPNL...2},{BPNL...3} "
    }
  ]
}
```

**Response**

```json
{....
  "constraintOperand": "Or",
  "constraints": [
    {
      "key": "BusinessPartnerNumber",
      "operator": "Equals",
      "value": "{BPNL...1}"
    },
    {
      "key": "BusinessPartnerNumber",
      "operator": "Equals",
      "value": "{BPNL...2}"
    },
    {
      "key": "BusinessPartnerNumber",
      "operator": "Equals",
      "value": "{BPNL...3}"
    }
  ]
}


Let me know in case we need further examples/scenarios - happy to provide them if I know what you need :)
