### ISSUE TITLE
Helm chart deployment fails when using external database instead of postgres dependency installation

### ISSUE THREAD

**Issue by niteshsakhiya** [eclipse-tractusx/policy-hub#70]
### Current Behavior
Helm chart deployment fails with the following error when using external database instead of postgres dependency.
`Error: template: policy-hub/charts/policy-hub/templates/secret-external-db.yaml:27:8: executing "policy-hub/charts/policy-hub/templates/secret-external-db.yaml" at <include "portal.labels" .>: error calling include: template: no template "portal.labels" associated with template "gotpl"`

Looks like "portal.labels" needs to be replaced by "phub.lables" in this helm template.   https://github.com/eclipse-tractusx/policy-hub/blob/5fdd7889b2f249c2ae5e8b8033553aafb8a118be/charts/policy-hub/templates/secret-external-db.yaml#L27

### Expected Behavior
The helm deployment should work when postgres dependency installation is disabled and external database details are added.

### Steps To Reproduce
Install the helm chart with the following helm values. 

_Disable the postgres dependency installation here._ 
https://github.com/eclipse-tractusx/policy-hub/blob/5fdd7889b2f249c2ae5e8b8033553aafb8a118be/charts/policy-hub/values.yaml#L120

_And add details of existing database in the externalDatabase here._ 
https://github.com/eclipse-tractusx/policy-hub/blob/5fdd7889b2f249c2ae5e8b8033553aafb8a118be/charts/policy-hub/values.yaml#L142

**Comment by evegufy** [comment]
Hi @niteshsakhiya thanks for reporting the issue, I noticed and fixed the issue last week https://github.com/eclipse-tractusx/policy-hub/pull/72, will be part of the next release

**Comment by niteshsakhiya** [comment]
Hi @evegufy ,
Thanks for fixing the issue and providing the update. 
I will close the issue. 
Cheers!
